# Generated by Django 3.1.2 on 2020-11-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_auto_20201101_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='value',
            field=models.IntegerField(default=2),
        ),
    ]
