# Generated by Django 3.1.2 on 2020-11-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0007_comment_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='value',
        ),
        migrations.AddField(
            model_name='comment',
            name='opinion',
            field=models.CharField(blank=True, choices=[('dislike', 'dislike'), ('like', 'like')], max_length=20),
        ),
    ]
