# Generated by Django 3.1.2 on 2020-11-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_auto_20201101_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='opinion',
        ),
        migrations.AddField(
            model_name='comment',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
