# Generated by Django 3.1.2 on 2020-11-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0009_auto_20201101_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='value',
        ),
        migrations.AddField(
            model_name='comment',
            name='opinion',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('dislike', 'dislike')], max_length=20),
        ),
    ]
